-- Name: YourNameHere
-- WatIAM username: IDhere
-- 
-- Details: This file inserts some example data into the database.
--          Example data can be used for testing other SQL queries
--          and/or testing an actual application.
--          
-- Warning: Read the homework for detailed instructions.